helm:
  parameters:
  - name: image.name
    value: docker.io/mosipid/config-server
    forcestring: true
  - name: image.tag
    value: 1.1.2@sha256:bc5ce50037d8988f807db45ee0fb19a750f6d0b17487155fca7edad0892e7eb0
    forcestring: true
