apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-secret-copier-binding
subjects:
- kind: ServiceAccount
  name: testingconfig
  namespace: {{ .Release.Namespace }}   # Replace with the namespace where the SA is created
roleRef:
  kind: ClusterRole
  name: configmap-secret-copier
  apiGroup: rbac.authorization.k8s.io
