helm:
  parameters:
  - name: image.name
    value: docker.io/bn1997/artifactory-server
    forcestring: true
  - name: image.tag
    value: main@sha256:89549e88610c58f417d728398d52a756aab8e17377830bf9fcf2b08da58e4e4f
    forcestring: true
