hooks:
  post-install:
  - kind: Job
    apiVersion: batch/v1beta1
    metadata:
      name: copy-configmaps
      namespace: {{ .Release.Namespace }}
    spec:
      template:
        metadata:
          name: copy-configmaps
        spec:
          restartPolicy: Never
          containers:
          - name: copy-configmaps
            image: busybox:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                for mapping in "global default" "keycloak-host keycloak" "activemq-activemq-artemis-share activemq" "s3 s3" "msg-gateways msg-gateways"; do
                  source_namespace=$(echo $mapping | cut -d' ' -f1)
                  configmap=$(echo $mapping | cut -d' ' -f2)
                  
                  kubectl get configmap $configmap -n $source_namespace -o yaml \
                    | sed "s/$source_namespace\/$configmap/config-server\/$configmap/" \
                    | kubectl apply -f -
                done
